### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by TonyBirt** [jmriego/emulation#9] opened 2023-07-04 21:11 UTC
Hi, using Kodi again after a bit of hiatus.  Getting the below traceback error, not sure what I might have wrong.  I am using a fresh install of kodi matrix 19.5 with just AEL 10.1 installed, a fresh install of Launchbox with Steam and Genesis added as platforms,  thanks Tony.

C:\Applications\Launchbox2AEL>launchbox2ael.py
Traceback (most recent call last):
  File "C:\Applications\Launchbox2AEL\LaunchBox2AEL.py", line 130, in <module>
    categories, launchers, collections = generate_data()
                                         ^^^^^^^^^^^^^^^
  File "C:\Applications\Launchbox2AEL\LaunchBox2AEL.py", line 35, in generate_data
    launchers = AELLaunchersCatalog(launchbox.games, DOSBOX_EXE, DOSBOX_ARGS, AELDIR)
                                    ^^^^^^^^^^^^^^^
  File "C:\Applications\Launchbox2AEL\launchbox\catalog.py", line 62, in games
    self.platforms,
    ^^^^^^^^^^^^^^
  File "C:\Applications\Launchbox2AEL\launchbox\catalog.py", line 48, in platforms
    self._platforms = PlatformsCatalog(
                      ^^^^^^^^^^^^^^^^^
  File "C:\Applications\Launchbox2AEL\launchbox\platform.py", line 35, in __init__
    self.platforms[platform_name].category = categories.search(category_name)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: ''

**Comment by jmriego** [comment] 2023-07-05 08:54
hi! I was recently starting to use Kodi again myself and doing some improvements.

From what I can see the issue seems to be that in LaunchBox you have a category assigned to a platform that does not exist. I think I know what the issue is but can you have a look at the LaunchBox file `Data/Platforms.xml` or attach it so I can have a look?

**Comment by TonyBirt** [comment] 2023-07-05 19:12
Thanks for taking a look, sorry Github won't let me attach it.

<?xml version="1.0" standalone="yes"?>
<LaunchBox>
  <Platform>
    <Category />
    <LocalDbParsed>true</LocalDbParsed>
    <Name>Sega Genesis</Name>
    <ReleaseDate>1989-08-14T19:00:00+12:00</ReleaseDate>
    <Developer>Sega Enterprises</Developer>
    <Manufacturer>Sega Enterprises</Manufacturer>
    <Cpu>Motorola 68000, Zilog Z80 co-processor</Cpu>
    <Memory>64 KB main RAM and 64 KB video RAM</Memory>
    <Graphics>Yahama YM7101 VDP</Graphics>
    <Sound>Yamaha YM2612, Texas Instruments SN76489A</Sound>
    <Display>256x224, 256x448, 320x224, 320x448</Display>
    <Media>ROM cartridge</Media>
    <MaxControllers>2</MaxControllers>
    <Folder />
    <Notes>The Sega Genesis, known as the Mega Drive in most regions outside North America, is a 16-bit home video game console which was developed and sold by Sega Enterprises, Ltd. The Genesis was Sega's third console and the successor to the Master System. Sega first released the console as the Mega Drive in Japan in 1988, followed by a North American debut under the Genesis moniker in 1989. In 1990, the console was distributed as the Mega Drive by Virgin Mastertronic in Europe, by Ozisoft in Australasia, and by Tec Toy in Brazil. In South Korea, the systems were distributed by Samsung and were known as the Super Gam*Boy, and later the Super Aladdin Boy.

The main microprocessor of the Genesis is a 16/32-bit Motorola 68000 CPU clocked at 7.6 MHz. The console also includes a Zilog Z80 sub-processor, which was mainly used to control the sound hardware and also provides backwards compatibility with the Master System.</Notes>
    <VideoPath />
    <HideInBigBox>false</HideInBigBox>
  </Platform>
  <Platform>
    <Category />
    <LocalDbParsed>true</LocalDbParsed>
    <Name>Windows</Name>
    <LastSelectedChild />
    <ReleaseDate>1985-11-20T21:00:00+13:00</ReleaseDate>
    <Developer>Microsoft</Developer>
    <Manufacturer />
    <Cpu />
    <Memory />
    <Graphics />
    <Sound />
    <Display />
    <Media />
    <MaxControllers />
    <Folder />
    <Notes>Microsoft introduced an operating environment named Windows on November 20, 1985 as a graphical operating system shell for MS-DOS in response to the growing interest in graphical user interfaces (GUIs). Microsoft Windows came to dominate the world's personal computer market with over 90% market share, overtaking Mac OS, which had been introduced in 1984.</Notes>
    <VideosFolder />
    <FrontImagesFolder />
    <BackImagesFolder />
    <ClearLogoImagesFolder />
    <FanartImagesFolder />
    <ScreenshotImagesFolder />
    <BannerImagesFolder />
    <SteamBannerImagesFolder />
    <ManualsFolder />
    <MusicFolder />
    <ScrapeAs />
    <VideoPath />
    <ImageType />
    <SortTitle />
    <LastGameId />
    <BigBoxView />
    <BigBoxTheme />
    <AndroidThemeVideoPath />
    <HideInBigBox>false</HideInBigBox>
  </Platform>
  <PlatformFolder>
    <MediaType>Box - Front</MediaType>
    <FolderPath>Images\Sega Genesis\Box - Front</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Box - Front - Reconstructed</MediaType>
    <FolderPath>Images\Sega Genesis\Box - Front - Reconstructed</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Box - Back</MediaType>
    <FolderPath>Images\Sega Genesis\Box - Back</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Box - Back - Reconstructed</MediaType>
    <FolderPath>Images\Sega Genesis\Box - Back - Reconstructed</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Box - 3D</MediaType>
    <FolderPath>Images\Sega Genesis\Box - 3D</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Box - Spine</MediaType>
    <FolderPath>Images\Sega Genesis\Box - Spine</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Box - Full</MediaType>
    <FolderPath>Images\Sega Genesis\Box - Full</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Advertisement Flyer - Front</MediaType>
    <FolderPath>Images\Sega Genesis\Advertisement Flyer - Front</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Advertisement Flyer - Back</MediaType>
    <FolderPath>Images\Sega Genesis\Advertisement Flyer - Back</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Arcade - Cabinet</MediaType>
    <FolderPath>Images\Sega Genesis\Arcade - Cabinet</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Arcade - Circuit Board</MediaType>
    <FolderPath>Images\Sega Genesis\Arcade - Circuit Board</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Arcade - Control Panel</MediaType>
    <FolderPath>Images\Sega Genesis\Arcade - Control Panel</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Arcade - Controls Information</MediaType>
    <FolderPath>Images\Sega Genesis\Arcade - Controls Information</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Arcade - Marquee</MediaType>
    <FolderPath>Images\Sega Genesis\Arcade - Marquee</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Banner</MediaType>
    <FolderPath>Images\Sega Genesis\Banner</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Cart - Front</MediaType>
    <FolderPath>Images\Sega Genesis\Cart - Front</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Cart - Back</MediaType>
    <FolderPath>Images\Sega Genesis\Cart - Back</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Cart - 3D</MediaType>
    <FolderPath>Images\Sega Genesis\Cart - 3D</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Clear Logo</MediaType>
    <FolderPath>Images\Sega Genesis\Clear Logo</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Disc</MediaType>
    <FolderPath>Images\Sega Genesis\Disc</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Fanart - Box - Front</MediaType>
    <FolderPath>Images\Sega Genesis\Fanart - Box - Front</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Fanart - Box - Back</MediaType>
    <FolderPath>Images\Sega Genesis\Fanart - Box - Back</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Fanart - Cart - Front</MediaType>
    <FolderPath>Images\Sega Genesis\Fanart - Cart - Front</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Fanart - Cart - Back</MediaType>
    <FolderPath>Images\Sega Genesis\Fanart - Cart - Back</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Fanart - Background</MediaType>
    <FolderPath>Images\Sega Genesis\Fanart - Background</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Fanart - Disc</MediaType>
    <FolderPath>Images\Sega Genesis\Fanart - Disc</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Screenshot - Gameplay</MediaType>
    <FolderPath>Images\Sega Genesis\Screenshot - Gameplay</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Screenshot - Game Title</MediaType>
    <FolderPath>Images\Sega Genesis\Screenshot - Game Title</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Screenshot - Game Select</MediaType>
    <FolderPath>Images\Sega Genesis\Screenshot - Game Select</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Screenshot - Game Over</MediaType>
    <FolderPath>Images\Sega Genesis\Screenshot - Game Over</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Screenshot - High Scores</MediaType>
    <FolderPath>Images\Sega Genesis\Screenshot - High Scores</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Steam Banner</MediaType>
    <FolderPath>Images\Sega Genesis\Steam Banner</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Steam Poster</MediaType>
    <FolderPath>Images\Sega Genesis\Steam Poster</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Steam Screenshot</MediaType>
    <FolderPath>Images\Sega Genesis\Steam Screenshot</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>GOG Poster</MediaType>
    <FolderPath>Images\Sega Genesis\GOG Poster</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>GOG Screenshot</MediaType>
    <FolderPath>Images\Sega Genesis\GOG Screenshot</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Epic Games Background</MediaType>
    <FolderPath>Images\Sega Genesis\Epic Games Background</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Epic Games Poster</MediaType>
    <FolderPath>Images\Sega Genesis\Epic Games Poster</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Epic Games Screenshot</MediaType>
    <FolderPath>Images\Sega Genesis\Epic Games Screenshot</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Origin Background</MediaType>
    <FolderPath>Images\Sega Genesis\Origin Background</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Origin Poster</MediaType>
    <FolderPath>Images\Sega Genesis\Origin Poster</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Origin Screenshot</MediaType>
    <FolderPath>Images\Sega Genesis\Origin Screenshot</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Uplay Background</MediaType>
    <FolderPath>Images\Sega Genesis\Uplay Background</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Uplay Thumbnail</MediaType>
    <FolderPath>Images\Sega Genesis\Uplay Thumbnail</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Amazon Background</MediaType>
    <FolderPath>Images\Sega Genesis\Amazon Background</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Amazon Screenshot</MediaType>
    <FolderPath>Images\Sega Genesis\Amazon Screenshot</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Amazon Poster</MediaType>
    <FolderPath>Images\Sega Genesis\Amazon Poster</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Video</MediaType>
    <FolderPath>Videos\Sega Genesis</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Theme Video</MediaType>
    <FolderPath>Videos\Sega Genesis\Theme</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Manual</MediaType>
    <FolderPath>Manuals\Sega Genesis</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Music</MediaType>
    <FolderPath>Music\Sega Genesis</FolderPath>
    <Platform>Sega Genesis</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Box - Front</MediaType>
    <FolderPath>Images\Windows\Box - Front</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Box - Front - Reconstructed</MediaType>
    <FolderPath>Images\Windows\Box - Front - Reconstructed</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Box - Back</MediaType>
    <FolderPath>Images\Windows\Box - Back</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Box - Back - Reconstructed</MediaType>
    <FolderPath>Images\Windows\Box - Back - Reconstructed</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Box - 3D</MediaType>
    <FolderPath>Images\Windows\Box - 3D</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Box - Spine</MediaType>
    <FolderPath>Images\Windows\Box - Spine</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Box - Full</MediaType>
    <FolderPath>Images\Windows\Box - Full</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Advertisement Flyer - Front</MediaType>
    <FolderPath>Images\Windows\Advertisement Flyer - Front</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Advertisement Flyer - Back</MediaType>
    <FolderPath>Images\Windows\Advertisement Flyer - Back</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Arcade - Cabinet</MediaType>
    <FolderPath>Images\Windows\Arcade - Cabinet</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Arcade - Circuit Board</MediaType>
    <FolderPath>Images\Windows\Arcade - Circuit Board</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Arcade - Control Panel</MediaType>
    <FolderPath>Images\Windows\Arcade - Control Panel</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Arcade - Controls Information</MediaType>
    <FolderPath>Images\Windows\Arcade - Controls Information</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Arcade - Marquee</MediaType>
    <FolderPath>Images\Windows\Arcade - Marquee</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Banner</MediaType>
    <FolderPath>Images\Windows\Banner</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Cart - Front</MediaType>
    <FolderPath>Images\Windows\Cart - Front</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Cart - Back</MediaType>
    <FolderPath>Images\Windows\Cart - Back</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Cart - 3D</MediaType>
    <FolderPath>Images\Windows\Cart - 3D</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Clear Logo</MediaType>
    <FolderPath>Images\Windows\Clear Logo</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Disc</MediaType>
    <FolderPath>Images\Windows\Disc</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Fanart - Box - Front</MediaType>
    <FolderPath>Images\Windows\Fanart - Box - Front</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Fanart - Box - Back</MediaType>
    <FolderPath>Images\Windows\Fanart - Box - Back</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Fanart - Cart - Front</MediaType>
    <FolderPath>Images\Windows\Fanart - Cart - Front</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Fanart - Cart - Back</MediaType>
    <FolderPath>Images\Windows\Fanart - Cart - Back</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Fanart - Background</MediaType>
    <FolderPath>Images\Windows\Fanart - Background</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Fanart - Disc</MediaType>
    <FolderPath>Images\Windows\Fanart - Disc</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Screenshot - Gameplay</MediaType>
    <FolderPath>Images\Windows\Screenshot - Gameplay</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Screenshot - Game Title</MediaType>
    <FolderPath>Images\Windows\Screenshot - Game Title</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Screenshot - Game Select</MediaType>
    <FolderPath>Images\Windows\Screenshot - Game Select</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Screenshot - Game Over</MediaType>
    <FolderPath>Images\Windows\Screenshot - Game Over</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Screenshot - High Scores</MediaType>
    <FolderPath>Images\Windows\Screenshot - High Scores</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Steam Banner</MediaType>
    <FolderPath>Images\Windows\Steam Banner</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Steam Poster</MediaType>
    <FolderPath>Images\Windows\Steam Poster</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Steam Screenshot</MediaType>
    <FolderPath>Images\Windows\Steam Screenshot</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>GOG Poster</MediaType>
    <FolderPath>Images\Windows\GOG Poster</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>GOG Screenshot</MediaType>
    <FolderPath>Images\Windows\GOG Screenshot</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Epic Games Background</MediaType>
    <FolderPath>Images\Windows\Epic Games Background</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Epic Games Poster</MediaType>
    <FolderPath>Images\Windows\Epic Games Poster</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Epic Games Screenshot</MediaType>
    <FolderPath>Images\Windows\Epic Games Screenshot</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Origin Background</MediaType>
    <FolderPath>Images\Windows\Origin Background</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Origin Poster</MediaType>
    <FolderPath>Images\Windows\Origin Poster</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Origin Screenshot</MediaType>
    <FolderPath>Images\Windows\Origin Screenshot</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Uplay Background</MediaType>
    <FolderPath>Images\Windows\Uplay Background</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Uplay Thumbnail</MediaType>
    <FolderPath>Images\Windows\Uplay Thumbnail</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Amazon Background</MediaType>
    <FolderPath>Images\Windows\Amazon Background</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Amazon Screenshot</MediaType>
    <FolderPath>Images\Windows\Amazon Screenshot</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Amazon Poster</MediaType>
    <FolderPath>Images\Windows\Amazon Poster</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Video</MediaType>
    <FolderPath>Videos\Windows</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Theme Video</MediaType>
    <FolderPath>Videos\Windows\Theme</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Manual</MediaType>
    <FolderPath>Manuals\Windows</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformFolder>
    <MediaType>Music</MediaType>
    <FolderPath>Music\Windows</FolderPath>
    <Platform>Windows</Platform>
  </PlatformFolder>
  <PlatformCategory>
    <Name>Computers</Name>
    <NestedName>Computers</NestedName>
    <Notes>Home computers were a class of microcomputers entering the market in 1977, and becoming common during the 1980s. They were marketed to consumers as affordable and accessible computers that, for the first time, were intended for the use of a single nontechnical user. These computers were a distinct market segment that typically cost much less than business, scientific or engineering-oriented computers of the time such as the IBM PC, and were generally less powerful in terms of memory and expandability. However, a home computer often had better graphics and sound than contemporaneous business computers. Their most common uses were playing video games, but they were also regularly used for word processing, doing homework, and programming.</Notes>
    <VideoPath />
    <SortTitle />
    <IsAutogenerated>false</IsAutogenerated>
    <ImageType />
    <Category />
    <LastGameId />
    <BigBoxView />
    <LocalDbParsed>false</LocalDbParsed>
    <Developer />
    <Manufacturer />
    <Cpu />
    <Memory />
    <Graphics />
    <Sound />
    <Display />
    <Media />
    <MaxControllers />
    <Folder />
    <VideosFolder />
    <FrontImagesFolder />
    <BackImagesFolder />
    <ClearLogoImagesFolder />
    <FanartImagesFolder />
    <ScreenshotImagesFolder />
    <BannerImagesFolder />
    <SteamBannerImagesFolder />
    <ManualsFolder />
    <MusicFolder />
    <ScrapeAs />
    <BigBoxTheme />
    <LastSelectedChild />
    <AndroidThemeVideoPath />
    <HideInBigBox>false</HideInBigBox>
  </PlatformCategory>
  <PlatformCategory>
    <Name>Consoles</Name>
    <NestedName>Consoles</NestedName>
    <Notes>A video game console is an electronic, digital or computer device that outputs a video signal or visual image to display a video game that one or more people can play. The term "video game console" is primarily used to distinguish a console machine primarily designed for consumers to use for playing video games, in contrast to arcade machines or home computers.

Although Ralph Baer had built working game consoles by 1966, it was nearly a decade before the Pong game made them commonplace in regular people's living rooms. Through evolution over the 1990s and 2000s, game consoles have expanded to offer additional functions such as CD players, DVD players, Blu-ray disc players, web browsers, set-top boxes and more.</Notes>
    <VideoPath />
    <IsAutogenerated>false</IsAutogenerated>
    <LocalDbParsed>false</LocalDbParsed>
    <Developer />
    <Manufacturer />
    <Cpu />
    <Memory />
    <Graphics />
    <Sound />
    <Display />
    <Media />
    <MaxControllers />
    <Folder />
    <HideInBigBox>false</HideInBigBox>
  </PlatformCategory>
</LaunchBox>

**Comment by TonyBirt** [comment] 2023-07-05 19:33
Attached as jpg, thanks for taking a look.

![Platforms](https://github.com/jmriego/emulation/assets/29388512/648c56b3-cfbc-470f-adb6-538bff24c615)

**Comment by jmriego** [comment] 2023-07-05 19:56
ah yes, I can see that file format is not supported. But it's not letting me see it as a JPG either
![image](https://github.com/jmriego/emulation/assets/15045950/9c4b342b-34dd-4683-9cc3-29311775f8c0)

what about if you copy that file as a .txt file? I think that should work

**Comment by TonyBirt** [comment] 2023-07-05 20:01
[Platforms.txt](https://github.com/jmriego/emulation/files/11961486/Platforms.txt)

Try that, thanks.

**Comment by jmriego** [comment] 2023-07-05 20:53
Thanks! do you mind also sending the Parents xml file? I think I'm getting close to the issue

**Comment by TonyBirt** [comment] 2023-07-05 20:56
[Parents.txt](https://github.com/jmriego/emulation/files/11962001/Parents.txt)

Great, attached

**Comment by jmriego** [comment] 2023-07-05 21:35
I think this should be good to go. I'll keep on doing some testing, but do you mind trying the `logger` branch? I have added the code in #10 to add better logging and fixing this issue

**Comment by TonyBirt** [comment] 2023-07-05 23:20
Adds category to AEL but say's category has no launchers.

D:\emulation-logger>
D:\emulation-logger>launchbox2ael.py
INFO:__main__:Reading LaunchBox data from D:\LaunchBox
INFO:__main__:Generating AEL categories from LaunchBox categories
INFO:__main__:Generating AEL launchers from LaunchBox platforms and emulators
WARNING:launchbox.platform:This category mapping doesnt seem to include a platform
WARNING:launchbox.platform:This category mapping doesnt seem to include a platform
INFO:launchbox.game:Generating list of Windows games
INFO:launchbox.game:Generating list of Sega Genesis games
INFO:ael.launcher:Generating list of AEL launchers from the games that use them
INFO:ael.launcher:Generating count of games for each AEL launcher
INFO:__main__:Generating AEL collections from LaunchBox playlists
INFO:__main__:Writing AEL categories
INFO:__main__:Writing AEL launchers
INFO:__main__:Writing launcher games
INFO:__main__:Writing collections file
INFO:__main__:Writing collections games

**Comment by jmriego** [comment] 2023-07-06 07:18
Are you referring to the warning saying `This category mapping doesnt seem to include a platform`? If that's it, it is expected and the rest of the data should be exported anyway.

I have separated the 4 category/platform parent relations that you have in the `Parents.xml` file. The script shoud have done this for each of those parents in this exact order:

1. Add Windows platform to the Computers category
2. There's a platform with no name added to the Computers category. Throws a warning
3. Add Sega Genesis platform to the Consoles category 
4. Add a not specified platform to the Consoles category. Throws a warning

The only two platforms with a category in your file are Computers/Windows and Consoles/Sega Genesis. If you open AEL you should see exactly that. Let me know if I'm missing anything

```
  <Parent>
    <PlatformName>Windows</PlatformName>
    <PlaylistId />
    <PlatformCategoryName />
    <ParentPlatformName />
    <ParentPlaylistId />
    <ParentPlatformCategoryName>Computers</ParentPlatformCategoryName>
  </Parent>

  <Parent>
    <PlatformName />
    <PlaylistId />
    <PlatformCategoryName>Computers</PlatformCategoryName>
    <ParentPlatformName />
    <ParentPlaylistId />
    <ParentPlatformCategoryName />
  </Parent>

  <Parent>
    <PlatformName>Sega Genesis</PlatformName>
    <ParentPlatformCategoryName>Consoles</ParentPlatformCategoryName>
  </Parent>

  <Parent>
    <PlatformCategoryName>Consoles</PlatformCategoryName>
  </Parent>
</LaunchBox>
```

**Comment by TonyBirt** [comment] 2023-07-06 19:41
Apologies, I might not be understanding.  The message I was mentioning was in Kodi itself.  
Advanced Emulator Launcher
Category Computers has no launchers.  Add Launchers first.

Logging adds category launchers to AEL but when opening AEL in Kodi it comes up with above message without games.  Sent a little something through Paypal for you help and time,  thanks.

**Comment by jmriego** [comment] 2023-07-06 22:19
ooh I see. I misunderstood what you were saying. I thought you meant the "category has no launchers" was something you were seeing in this program.
just a guess... you probably have games, but just in case. Do you have games added to LaunchBox in the Windows platform?

It might be best if you edit the `config.ini` file and you add this text to it:
```
[debug]
file=LaunchBox2AEL.log
```

Then run the export and attach here the `LaunchBox2AEL.log` file that will be generated and should have a lot of detail for what it's doing internally that I can review. And thank you so much for the donation!

**Comment by TonyBirt** [comment] 2023-07-06 22:48
Cheers, renamed log to txt and attached.

[LaunchBox2AEL.txt](https://github.com/jmriego/emulation/files/11973036/LaunchBox2AEL.txt)

**Comment by jmriego** [comment] 2023-07-07 16:27
I was finally able to reproduce it. Can you try again with the code in this same `logger` branch? 🤞

**Comment by jmriego** [comment] 2023-07-14 20:58
hi! did you manage to check if this fixed it for you? I think this is ready unless you found some issue

**Closed as completed** 2023-07-20 18:51 UTC
